// src/App.tsx
import { BrowserRouter, Routes, Route } from 'react-router-dom';
import { Layout } from './components/Layout';
import { HomePage } from './pages/HomePage';
import { MagesPage } from './pages/MagesPage';

function App() {
  return (
    <BrowserRouter>
      <Routes>
        <Route path="/" element={<Layout />}>
          <Route index element={<HomePage />} />
          <Route path="mages" element={<MagesPage />} />
        </Route>
      </Routes>
    </BrowserRouter>
  );
}

export default App;

// src/App.svelte
<script lang="ts">
    import { Router, Route } from "svelte-routing";
    import Layout from "./components/Layout.svelte";
    import HomePage from "./pages/HomePage.svelte";
    import MagesPage from "./pages/MagesPage.svelte";
    import MageDetailsPage from "./pages/MageDetailsPage.svelte";

    export let url = "";
</script>

<Router {url}>
    <Layout>
        <Route path="/">
            <HomePage />
        </Route>
        <Route path="/mages">
            <MagesPage />
        </Route>
        <Route path="/mages/:id" let:params>
            <MageDetailsPage id={params.id} />
        </Route>
    </Layout>
</Router>
